### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by wmichaeltaylor** [cyber-sushi/pipewire-sample-rate-config#1]
Could you explain in a straightforward way how I can run this file?

**Comment by cyber-sushi** [comment]
Assuming you have `python3` and `tk` installed on your system (on Arch-based distros, the package is just `python`):

**GUI:**
Right click on the file > Properties > Permissions > Allow executing file as a program
Then, if you're using Nautilus as your file manager, Right click > Run as Program
If you're using Nemo, just double click > Run

**CLI:**
`cd` to the file directory, for example `cd Downloads`
`chmod +x main.py` to make it executable
`./main.py` to execute it
