### ISSUE TITLE
Feature request: Update to include buffer size.

### ISSUE THREAD

**Issue by mcoyle1960** [cyber-sushi/pipewire-sample-rate-config#2]
Great little utility. When you have some free time (!), is there any chance you can add the ability to also force the  buffer size? 

Thanks for you work.

**Comment by cyber-sushi** [comment]
Done, I've also refactored the code for simplicity, let me know if it works as expected

**Comment by mcoyle1960** [comment]
You sir, are awesome. 
Thank you very much.
